### PR TITLE
Added configuration for the jinja environment variables

### PR DESCRIPTION
**Pull request by TomSmartBishop**

### CODE REVIEW

**Comment by filwaitman** [comment]
Hey @TomSmartBishop, thanks for the PR!

I'm a bit busy lately but I'll review it as soon as I have time!  =]

**Comment by TomSmartBishop** [comment]
No worries, whenever you have time.

**Comment by TomSmartBishop** [comment]
Hey @filwaitman , any update?

**Comment by filwaitman** [comment]
@TomSmartBishop I'm heading back home tomorrow, so I'll look this tomorrow/Friday. Sorry for the delay.

**Comment by filwaitman** [comment]
hey @TomSmartBishop I just took a look and sound great! There are a few minor PEP8 things but I'll fix those on my side. Many thanks for the PR (and for the patience  :laughing: )!

**Comment by TomSmartBishop** [comment]
@filwaitman Alright, is there any command line tool to auto correct PEP8 issues?

**Comment by TomSmartBishop** [comment]
Never mind, just found this: http://stackoverflow.com/questions/14328406/tool-to-convert-python-code-to-be-pep8-compliant

**Comment by filwaitman** [comment]
@TomSmartBishop don't worry that much about it. Fixing PEP8 is the simplest part on your pull requests.  =)

**Pull request merged**
